Error at date 05/02/2022 19:50:
[+] While reading the file: 20-01-27 - MAKRO - 0-0(014)0006-(2020)027031.pdf
[+] The type of the error was: IndexError
The text was:
[+] File "C:\Users\osgum\github\Zotz\main.py", line 105, in run
[+]   Excel(excel, pdf, self)
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 54, in __init__
[+]   self.write_items()
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 132, in write_items
[+]   self.ws[f'D{self.row}'] = list(db.show_one_row(
[+]	IndexError: list index out of range

