Error at date 04/03/2022 15:01:
[+] While reading the file: 21-12-16 - Mercadona - A-V2021-00004340365.pdf
[+] The type of the error was: IndexError
The text was:
[+] File "C:\Users\osgum\github\Zotz\main.py", line 105, in run
[+]   Excel(excel, pdf, self)
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 62, in __init__
[+]   self.write_items()
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 146, in write_items
[+]   self.ws[f'D{self.row}'] = list(db.show_one_row(
[+]	IndexError: list index out of range

