Error at date 27/01/2022 12:50:
[+] While reading the file: 20-01-27 - MAKRO - 0-0(014)0006-(2020)027031.pdf
[+] The type of the error was: AttributeError
The text was:
[+] File "C:\Users\osgum\github\Zotz\main.py", line 105, in run
[+]   Excel(excel, pdf, self)
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 26, in __init__
[+]   self.new, self.bill = self.select_case(pdf)
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 83, in select_case
[+]   'MAKRO' : Makro(pdf),
[+] File "C:\Users\osgum\github\Zotz\makro.py", line 39, in __init__
[+]   self.get_bill_num()
[+] File "C:\Users\osgum\github\Zotz\makro.py", line 105, in get_bill_num
[+]   self.factura[row[0]] = row[1:3].replace('/', '-')
[+]	AttributeError: 'list' object has no attribute 'replace'

Error at date 27/01/2022 13:11:
[+] While reading the file: 21-01-12 - Mercadona - A-V2021-00000092225.pdf
[+] The type of the error was: IndexError
The text was:
[+] File "C:\Users\osgum\github\Zotz\main.py", line 105, in run
[+]   Excel(excel, pdf, self)
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 54, in __init__
[+]   self.write_items()
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 129, in write_items
[+]   self.ws[f'D{self.row}'] = list(db.show_one_row(
[+]	IndexError: list index out of range

Error at date 27/01/2022 15:31:
[+] While reading the file: 21-01-12 - Mercadona - A-V2021-00000092225.pdf
[+] The type of the error was: IndexError
The text was:
[+] File "C:\Users\osgum\github\Zotz\main.py", line 105, in run
[+]   Excel(excel, pdf, self)
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 54, in __init__
[+]   self.write_items()
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 132, in write_items
[+]   self.ws[f'D{self.row}'] = list(db.show_one_row(
[+]	IndexError: list index out of range

Error at date 27/01/2022 15:32:
[+] While reading the file: 21-01-12 - Mercadona - A-V2021-00000092225.pdf
[+] The type of the error was: IndexError
The text was:
[+] File "C:\Users\osgum\github\Zotz\main.py", line 105, in run
[+]   Excel(excel, pdf, self)
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 54, in __init__
[+]   self.write_items()
[+] File "C:\Users\osgum\github\Zotz\siguiente.py", line 132, in write_items
[+]   self.ws[f'D{self.row}'] = list(db.show_one_row(
[+]	IndexError: list index out of range

