Error at date 19/03/2022 21:10:
[+] While reading the file: 21-01-07 - MAKRO - 0-0(014)0007-(2021)007019.pdf
[+] The type of the error was: AttributeError
The text was:
[+] File "main.py", line 105, in run
[+] File "siguiente.py", line 62, in __init__
[+]   self.write_items()
[+] File "siguiente.py", line 156, in write_items
[+]   self.insert_new_row()
[+] File "siguiente.py", line 164, in insert_new_row
[+]   self.ws[f'L{self.row+1}'] = self.ws[f'L{self.row}'].value\
[+]	AttributeError: 'NoneType' object has no attribute 'replace'

Error at date 19/03/2022 21:15:
[+] While reading the file: 21-01-07 - MAKRO - 0-0(014)0007-(2021)007019.pdf
[+] The type of the error was: AttributeError
The text was:
[+] File "main.py", line 105, in run
[+] File "siguiente.py", line 62, in __init__
[+]   self.write_items()
[+] File "siguiente.py", line 156, in write_items
[+]   self.insert_new_row()
[+] File "siguiente.py", line 164, in insert_new_row
[+]   self.ws[f'L{self.row+1}'] = str(self.ws[f'L{self.row}'].value)\
[+]	AttributeError: 'NoneType' object has no attribute 'replace'

Error at date 22/03/2022 18:08:
[+] While reading the file: 21-01-02 - LIDL - 2021401600286.pdf
[+] The type of the error was: IndexError
The text was:
[+] File "main.py", line 105, in run
[+] File "siguiente.py", line 63, in __init__
[+]   # Escribimos los descuentos si existen:
[+] File "siguiente.py", line 147, in write_items
[+]   self.prov, 'Codigo', item['codigo']))[0][2]
[+]	IndexError: list index out of range

